# Generated by Django 4.0.4 on 2022-05-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_examen_parcial', '0002_canciones_peliculas_series_videojuegos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canciones',
            name='album',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canciones',
            name='banda',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canciones',
            name='titulo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='casa_productora',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='descripcion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='titulo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='casa_productora',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='descripcion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='titulo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='videojuegos',
            name='casa_desarrolladora',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='videojuegos',
            name='titulo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
